verbose=false
max_width=1000
ideal_width=1000
tabs_spaces=4
fn_call_width=1000
struct_lit_width=32
fn_arg_indent="Tabbed"
single_line_if_else=true
where_indent="Visual"
where_trailing_comma=true
chain_base_indent="Inherit"
chain_indent="Inherit"
reorder_imports=true
format_strings=false
chain_overflow_last=false
hard_tabs=true
wrap_match_arms=false
